export const mockedParamsValues = {
  metaData: {},
  resource: {
    paramName: 'timeStampFormat',
    paramValues: [
      { name: "yyyy-MM-dd'T'HH:mm:ss*SSSZZZZ", value: "yyyy-MM-dd'T'HH:mm:ss*SSSZZZZ" },
      { name: 'yyyy MMM dd HH:mm:ss.SSS zzz', value: 'yyyy MMM dd HH:mm:ss.SSS zzz' },
      { name: 'MMM dd HH:mm:ss ZZZZ yyyy', value: 'MMM dd HH:mm:ss ZZZZ yyyy' },
      { name: 'dd/MMM/yyyy:HH:mm:ss ZZZZ', value: 'dd/MMM/yyyy:HH:mm:ss ZZZZ' },
      { name: 'MMM dd, yyyy hh:mm:ss a', value: 'MMM dd, yyyy hh:mm:ss a' },
      { name: 'MMM dd yyyy HH:mm:ss', value: 'MMM dd yyyy HH:mm:ss' },
      { name: 'MMM dd HH:mm:ss yyyy', value: 'MMM dd HH:mm:ss yyyy' },
      { name: 'MMM dd HH:mm:ss ZZZZ', value: 'MMM dd HH:mm:ss ZZZZ' },
      { name: 'MMM dd HH:mm:ss', value: 'MMM dd HH:mm:ss' },
      { name: "yyyy-MM-dd'T'HH:mm:ssZZZZ", value: "yyyy-MM-dd'T'HH:mm:ssZZZZ" },
      { name: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", value: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'" },
      { name: "yyyy-MM-dd'T'HH:mm:ss.SSSX", value: "yyyy-MM-dd'T'HH:mm:ss.SSSX" },
      { name: 'yyyy-MM-dd HH:mm:ss ZZZZ', value: 'yyyy-MM-dd HH:mm:ss ZZZZ' },
      { name: 'yyyy-MM-dd HH:mm:ssZZZZ', value: 'yyyy-MM-dd HH:mm:ssZZZZ' },
      { name: 'yyyy-MM-dd HH:mm:ss,SSS', value: 'yyyy-MM-dd HH:mm:ss,SSS' },
      { name: 'yyyy/MM/dd*HH:mm:ss', value: 'yyyy/MM/dd*HH:mm:ss' },
      { name: 'yyyy MMM dd HH:mm:ss.SSS*zzz', value: 'yyyy MMM dd HH:mm:ss.SSS*zzz' },
      { name: 'yyyy MMM dd HH:mm:ss.SSS', value: 'yyyy MMM dd HH:mm:ss.SSS' },
      { name: 'yyyy-MM-dd HH:mm:ss,SSSZZZZ', value: 'yyyy-MM-dd HH:mm:ss,SSSZZZZ' },
      { name: 'yyyy-MM-dd HH:mm:ss.SSS', value: 'yyyy-MM-dd HH:mm:ss.SSS' },
      { name: 'yyyy-MM-dd HH:mm:ss.SSSZZZZ', value: 'yyyy-MM-dd HH:mm:ss.SSSZZZZ' },
      { name: "yyyy-MM-dd'T'HH:mm:ss.SSS", value: "yyyy-MM-dd'T'HH:mm:ss.SSS" },
      { name: "yyyy-MM-dd'T'HH:mm:ss", value: "yyyy-MM-dd'T'HH:mm:ss" },
      { name: "yyyy-MM-dd'T'HH:mm:ss'Z'", value: "yyyy-MM-dd'T'HH:mm:ss'Z'" },
      { name: "yyyy-MM-dd'T'HH:mm:ss.SSS", value: "yyyy-MM-dd'T'HH:mm:ss.SSS" },
      { name: "yyyy-MM-dd'T'HH:mm:ss", value: "yyyy-MM-dd'T'HH:mm:ss" },
      { name: 'yyyy-MM-dd*HH:mm:ss:SSS', value: 'yyyy-MM-dd*HH:mm:ss:SSS' },
      { name: 'yyyy-MM-dd*HH:mm:ss', value: 'yyyy-MM-dd*HH:mm:ss' },
      { name: 'yy-MM-dd HH:mm:ss,SSS ZZZZ', value: 'yy-MM-dd HH:mm:ss,SSS ZZZZ' },
      { name: 'yy-MM-dd HH:mm:ss,SSS', value: 'yy-MM-dd HH:mm:ss,SSS' },
      { name: 'yy-MM-dd HH:mm:ss', value: 'yy-MM-dd HH:mm:ss' },
      { name: 'yy/MM/dd HH:mm:ss', value: 'yy/MM/dd HH:mm:ss' },
      { name: 'yyMMdd HH:mm:ss', value: 'yyMMdd HH:mm:ss' },
      { name: 'yyyyMMdd HH:mm:ss.SSS', value: 'yyyyMMdd HH:mm:ss.SSS' },
      { name: 'MM/dd/yy*HH:mm:ss', value: 'MM/dd/yy*HH:mm:ss' },
      { name: 'MM/dd/yyyy*HH:mm:ss', value: 'MM/dd/yyyy*HH:mm:ss' },
      { name: 'MM/dd/yyyy*HH:mm:ss*SSS', value: 'MM/dd/yyyy*HH:mm:ss*SSS' },
      { name: 'MM/dd/yy HH:mm:ss ZZZZ', value: 'MM/dd/yy HH:mm:ss ZZZZ' },
      { name: 'MM/dd/yyyy HH:mm:ss ZZZZ', value: 'MM/dd/yyyy HH:mm:ss ZZZZ' },
      { name: 'HH:mm:ss', value: 'HH:mm:ss' },
      { name: 'HH:mm:ss.SSS', value: 'HH:mm:ss.SSS' },
      { name: 'HH:mm:ss,SSS', value: 'HH:mm:ss,SSS' },
      { name: 'dd/MMM HH:mm:ss,SSS', value: 'dd/MMM HH:mm:ss,SSS' },
      { name: 'dd/MMM/yyyy:HH:mm:ss', value: 'dd/MMM/yyyy:HH:mm:ss' },
      { name: 'dd-MMM-yyyy HH:mm:ss', value: 'dd-MMM-yyyy HH:mm:ss' },
      { name: 'dd-MMM-yyyy HH:mm:ss.SSS', value: 'dd-MMM-yyyy HH:mm:ss.SSS' },
      { name: 'dd MMM yyyy HH:mm:ss', value: 'dd MMM yyyy HH:mm:ss' },
      { name: 'dd MMM yyyy HH:mm:ss*SSS', value: 'dd MMM yyyy HH:mm:ss*SSS' },
      { name: 'MMdd_HH:mm:ss', value: 'MMdd_HH:mm:ss' },
      { name: 'MMdd_HH:mm:ss.SSS', value: 'MMdd_HH:mm:ss.SSS' },
      { name: 'MM/dd/yyyy hh:mm:ss a:SSS', value: 'MM/dd/yyyy hh:mm:ss a:SSS' },
      { name: 'MM/dd/yyyy hh:mm:ss a', value: 'MM/dd/yyyy hh:mm:ss a' }
    ]
  },
  responseMessages: []
}
