/*
 * Copyright 2023 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Shield 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.
 */

/**
 * Generated by @openapi-codegen
 *
 * @version 0.1
 */
export type CETLicenseUsageDTO = {
  accountIdentifier?: string
  module?: string
  /**
   * @format int64
   */
  timestamp?: number
  numberOfAgents?: UsageDataDTO
}

export type ReferenceDTO = {
  name?: string
  identifier?: string
  projectIdentifier?: string
  orgIdentifier?: string
  accountIdentifier?: string
  /**
   * @format int64
   */
  count?: number
}

export type UsageDataDTO = {
  /**
   * @format int64
   */
  count?: number
  displayName?: string
  references?: ReferenceDTO[]
}

/**
 * @example {"message":"Not Found","status":404}
 */
export type NotFound = {
  /**
   * @example Not Found
   */
  message: string
  /**
   * @default 404
   * @example 404
   * @format int64
   */
  status?: number
}
