/*
 * Copyright 2023 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Shield 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.
 */

/* Generated by restful-react */

import React from 'react'
import { Get, GetProps, useGet, UseGetProps } from 'restful-react'

import { getConfig, getUsingFetch, GetUsingFetchProps } from '../config'
export const SPEC_VERSION = '1.0.0'
export interface CHAOSLicenseUsageDTO {
  accountIdentifier?: string
  experimentRunsPerMonth?: UsageDataDTO
  module?: string
  timestamp?: number
}

export interface ChaosExperimentRunsStatsResponse {
  data?: ExperimentRunsData
}

export interface ExperimentRunStats {
  failed?: number
  success?: number
  time?: number
}

export interface ExperimentRunsData {
  experimentRunStats?: ExperimentRunStats[]
  totalExperimentChange?: number
  totalExperimentRuns?: number
}

export interface ReferenceDTO {
  accountIdentifier?: string
  identifier?: string
  name?: string
  orgIdentifier?: string
  projectIdentifier?: string
}

export interface UsageDataDTO {
  count?: number
  displayName?: string
  references?: ReferenceDTO[]
}

export interface GetChaosExperimentStatsQueryParams {
  accountIdentifier: string
  startTime: number
  endTime: number
  groupBy?: 'DAY' | 'WEEK' | 'MONTH'
}

export type GetChaosExperimentStatsProps = Omit<
  GetProps<ChaosExperimentRunsStatsResponse, void, GetChaosExperimentStatsQueryParams, void>,
  'path'
>

/**
 * Get overview stats for chaos experiments
 *
 * Get overview stats for chaos experiments for a specific account
 */
export const GetChaosExperimentStats = (props: GetChaosExperimentStatsProps) => (
  <Get<ChaosExperimentRunsStatsResponse, void, GetChaosExperimentStatsQueryParams, void>
    path={`/overview/experiment-stats`}
    base={getConfig('chaos/manager/api/rest')}
    {...props}
  />
)

export type UseGetChaosExperimentStatsProps = Omit<
  UseGetProps<ChaosExperimentRunsStatsResponse, void, GetChaosExperimentStatsQueryParams, void>,
  'path'
>

/**
 * Get overview stats for chaos experiments
 *
 * Get overview stats for chaos experiments for a specific account
 */
export const useGetChaosExperimentStats = (props: UseGetChaosExperimentStatsProps) =>
  useGet<ChaosExperimentRunsStatsResponse, void, GetChaosExperimentStatsQueryParams, void>(
    `/overview/experiment-stats`,
    { base: getConfig('chaos/manager/api/rest'), ...props }
  )

/**
 * Get overview stats for chaos experiments
 *
 * Get overview stats for chaos experiments for a specific account
 */
export const getChaosExperimentStatsPromise = (
  props: GetUsingFetchProps<ChaosExperimentRunsStatsResponse, void, GetChaosExperimentStatsQueryParams, void>,
  signal?: RequestInit['signal']
) =>
  getUsingFetch<ChaosExperimentRunsStatsResponse, void, GetChaosExperimentStatsQueryParams, void>(
    getConfig('chaos/manager/api/rest'),
    `/overview/experiment-stats`,
    props,
    signal
  )

export interface GetChaosLicenseUsageQueryParams {
  /**
   * Account identifier that is searching at
   */
  accountIdentifier: string
}

export type GetChaosLicenseUsageProps = Omit<
  GetProps<CHAOSLicenseUsageDTO, void, GetChaosLicenseUsageQueryParams, void>,
  'path'
>

/**
 * Find current license usage for chaos data by accountIdentifier
 *
 * Query current chaos license usage data for an account.
 */
export const GetChaosLicenseUsage = (props: GetChaosLicenseUsageProps) => (
  <Get<CHAOSLicenseUsageDTO, void, GetChaosLicenseUsageQueryParams, void>
    path={`/usage`}
    base={getConfig('chaos/manager/api/rest')}
    {...props}
  />
)

export type UseGetChaosLicenseUsageProps = Omit<
  UseGetProps<CHAOSLicenseUsageDTO, void, GetChaosLicenseUsageQueryParams, void>,
  'path'
>

/**
 * Find current license usage for chaos data by accountIdentifier
 *
 * Query current chaos license usage data for an account.
 */
export const useGetChaosLicenseUsage = (props: UseGetChaosLicenseUsageProps) =>
  useGet<CHAOSLicenseUsageDTO, void, GetChaosLicenseUsageQueryParams, void>(`/usage`, {
    base: getConfig('chaos/manager/api/rest'),
    ...props
  })

/**
 * Find current license usage for chaos data by accountIdentifier
 *
 * Query current chaos license usage data for an account.
 */
export const getChaosLicenseUsagePromise = (
  props: GetUsingFetchProps<CHAOSLicenseUsageDTO, void, GetChaosLicenseUsageQueryParams, void>,
  signal?: RequestInit['signal']
) =>
  getUsingFetch<CHAOSLicenseUsageDTO, void, GetChaosLicenseUsageQueryParams, void>(
    getConfig('chaos/manager/api/rest'),
    `/usage`,
    props,
    signal
  )
