export enum ServiceOverridesTab {
  ENVIRONMENT_GLOBAL = 'ENVIRONMENT_GLOBAL',
  ENVIRONMENT_SERVICE_SPECIFIC = 'ENVIRONMENT_SERVICE_SPECIFIC',
  INFRA_GLOBAL = 'INFRA_GLOBAL',
  INFRA_SERVICE_SPECIFIC = 'INFRA_SERVICE_SPECIFIC'
}
