/*
 * Copyright 2023 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Shield 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.
 */
/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import { useMutation, UseMutationOptions } from '@tanstack/react-query'

import type { ResponseListAmiTagObject } from '../schemas/ResponseListAmiTagObject'
import type { Failure } from '../schemas/Failure'
import type { Error } from '../schemas/Error'
import type { ListTagsForAmiArtifactBodyRequestBody } from '../requestBodies/ListTagsForAmiArtifactBodyRequestBody'
import { fetcher, FetcherOptions } from 'services/fetcher'

export interface ListTagsForAmiArtifactMutationQueryParams {
  connectorRef?: string
  region?: string
  accountIdentifier: string
  orgIdentifier?: string
  projectIdentifier?: string
  pipelineIdentifier?: string
  fqnPath?: string
  serviceId?: string
  branch?: string
  repoIdentifier?: string
  getDefaultFromOtherRepo?: boolean
  parentEntityConnectorRef?: string
  parentEntityRepoName?: string
  parentEntityAccountIdentifier?: string
  parentEntityOrgIdentifier?: string
  parentEntityProjectIdentifier?: string
  repoName?: string
}

export type ListTagsForAmiArtifactRequestBody = ListTagsForAmiArtifactBodyRequestBody

export type ListTagsForAmiArtifactOkResponse = ResponseListAmiTagObject

export type ListTagsForAmiArtifactErrorResponse = Failure | Error

export interface ListTagsForAmiArtifactProps
  extends Omit<FetcherOptions<ListTagsForAmiArtifactMutationQueryParams, ListTagsForAmiArtifactRequestBody>, 'url'> {
  queryParams: ListTagsForAmiArtifactMutationQueryParams
  body: ListTagsForAmiArtifactRequestBody
}

export function listTagsForAmiArtifact(props: ListTagsForAmiArtifactProps): Promise<ListTagsForAmiArtifactOkResponse> {
  const { ...rest } = props

  return fetcher<
    ListTagsForAmiArtifactOkResponse,
    ListTagsForAmiArtifactMutationQueryParams,
    ListTagsForAmiArtifactRequestBody
  >({
    url: `ng/api/artifacts/ami/tags`,
    method: 'POST',
    ...rest
  })
}

/**
 *
 */
export function useListTagsForAmiArtifactMutation(
  props: ListTagsForAmiArtifactProps,
  options?: Omit<
    UseMutationOptions<ListTagsForAmiArtifactOkResponse, ListTagsForAmiArtifactErrorResponse>,
    'mutationKey' | 'mutationFn'
  >
) {
  return useMutation<ListTagsForAmiArtifactOkResponse, ListTagsForAmiArtifactErrorResponse>(
    () => listTagsForAmiArtifact(props),
    options
  )
}
