/*
 * Copyright 2022 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Shield 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.
 */
/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

export interface ExecutionSummaryInfo {
  deployments?: number[]
  lastExecutionId?: string
  lastExecutionStatus?:
    | 'APPROVAL_REJECTED'
    | 'APPROVAL_WAITING'
    | 'Aborted'
    | 'AbortedByFreeze'
    | 'ApprovalRejected'
    | 'ApprovalWaiting'
    | 'AsyncWaiting'
    | 'Discontinuing'
    | 'Errored'
    | 'Expired'
    | 'Failed'
    | 'INTERVENTION_WAITING'
    | 'IgnoreFailed'
    | 'InputWaiting'
    | 'InterventionWaiting'
    | 'NOT_STARTED'
    | 'NotStarted'
    | 'Paused'
    | 'Pausing'
    | 'Queued'
    | 'ResourceWaiting'
    | 'Running'
    | 'Skipped'
    | 'Success'
    | 'Suspended'
    | 'TaskWaiting'
    | 'TimedWaiting'
    | 'WAITING'
    | 'WaitStepRunning'
  /**
   * @format int64
   */
  lastExecutionTs?: number
  numOfErrors?: number[]
}
