/*
 * Copyright 2022 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Shield 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.
 */
/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { EntityValidityDetails } from '../schemas/EntityValidityDetails'
import type { ExecutionSummaryInfo } from '../schemas/ExecutionSummaryInfo'
import type { EntityGitDetails } from '../schemas/EntityGitDetails'
import type { RecentExecutionInfoDto } from '../schemas/RecentExecutionInfoDto'

export interface PmsPipelineSummaryResponse {
  connectorRef?: string
  /**
   * @format int64
   */
  createdAt?: number
  description?: string
  entityValidityDetails?: EntityValidityDetails
  executionSummaryInfo?: ExecutionSummaryInfo
  filters?: { [key: string]: { [key: string]: { [key: string]: any } } }
  gitDetails?: EntityGitDetails
  identifier?: string
  isDraft?: boolean
  /**
   * @format int64
   */
  lastUpdatedAt?: number
  modules?: string[]
  name?: string
  /**
   * @format int32
   */
  numOfStages?: number
  recentExecutionsInfo?: RecentExecutionInfoDto[]
  stageNames?: string[]
  storeType?: 'INLINE' | 'REMOTE'
  tags?: { [key: string]: string }
  /**
   * @format int64
   */
  version?: number
}
