/*
 * Copyright 2023 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Shield 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.
 */
/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { ExecutorInfoDto } from '../schemas/ExecutorInfoDto'
import type { PipelineStageInfo } from '../schemas/PipelineStageInfo'

export interface RecentExecutionInfoDto {
  /**
   * @format int64
   */
  endTs?: number
  executorInfo?: ExecutorInfoDto
  parentStageInfo?: PipelineStageInfo
  planExecutionId?: string
  /**
   * @format int32
   */
  runSequence?: number
  /**
   * @format int64
   */
  startTs?: number
  status?:
    | 'APPROVAL_REJECTED'
    | 'APPROVAL_WAITING'
    | 'Aborted'
    | 'AbortedByFreeze'
    | 'ApprovalRejected'
    | 'ApprovalWaiting'
    | 'AsyncWaiting'
    | 'Discontinuing'
    | 'Errored'
    | 'Expired'
    | 'Failed'
    | 'INTERVENTION_WAITING'
    | 'IgnoreFailed'
    | 'InputWaiting'
    | 'InterventionWaiting'
    | 'NOT_STARTED'
    | 'NotStarted'
    | 'Paused'
    | 'Pausing'
    | 'Queued'
    | 'QueuedExecutionConcurrencyReached'
    | 'QueuedLicenseLimitReached'
    | 'ResourceWaiting'
    | 'Running'
    | 'Skipped'
    | 'Success'
    | 'Suspended'
    | 'TaskWaiting'
    | 'TimedWaiting'
    | 'WAITING'
    | 'WaitStepRunning'
}
