/*
 * Copyright 2022 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Shield 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.
 */
/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { EntityValidityDetails } from '../schemas/EntityValidityDetails'
import type { EntityGitDetails } from '../schemas/EntityGitDetails'

export interface TemplateResponse {
  accountId: string
  childType?: string
  connectorRef?: string
  description?: string
  entityValidityDetails?: EntityValidityDetails
  gitDetails?: EntityGitDetails
  icon?: string
  identifier: string
  /**
   * @format int64
   */
  lastUpdatedAt?: number
  name: string
  orgIdentifier?: string
  projectIdentifier?: string
  stableTemplate?: boolean
  storeType?: 'INLINE' | 'REMOTE'
  tags?: { [key: string]: string }
  templateEntityType?:
    | 'ArtifactSource'
    | 'CustomDeployment'
    | 'MonitoredService'
    | 'Pipeline'
    | 'SecretManager'
    | 'Stage'
    | 'Step'
  templateScope?: 'account' | 'org' | 'project' | 'unknown'
  /**
   * @format int64
   */
  version?: number
  versionLabel?: string
  yaml?: string
}
