/**
 * Generated by @openapi-codegen
 *
 * @version 0.1.0-beta
 */
/**
 * @example {"message":"Bad Request: accountId parameter is required","status":400}
 */
export type BadRequest = {
  /*
   * @example Bad Request: accountId parameter is required
   */
  message: string
  /*
   * @default 400
   * @example 400
   * @format int64
   */
  status?: number
}

/**
 * @example {"description":"This is the very long ticket description...","exists":false,"externalId":"ABC-1234","identifiers":{"idName":["value1","value2","value3"]},"issueType":"Bug","module":"sto","priority":"High","projectKey":"ABC","title":"A new ticket"}
 */
export type CreateTicketRequestBody = {
  /*
   * The description for this External Ticket
   *
   * @example This is the very long ticket description...
   */
  description?: string
  /*
   * Indicates the ticket already exists on the ticket provider
   *
   * @example false
   */
  exists?: boolean
  /*
   * The ID used to identify this External Ticket in the ticket provider. Only used if the "exists" field is true.
   *
   * @example ABC-1234
   */
  externalId?: string
  /*
   * Identifier(s) to associate with this ticket, in "key":"value" and/or "key":ArrayOf("values"...) form
   *
   * @example {"idName":["value1","value2","value3"]}
   */
  identifiers: {
    [key: string]: any
  }
  /*
   * The Jira issue type to use for this External Ticket
   *
   * @example Bug
   */
  issueType?: string
  /*
   * The Harness module responsible for this ticket
   *
   * @example sto
   */
  module: string
  /*
   * The priority to use for this External Ticket
   *
   * @example High
   */
  priority?: string
  /*
   * The Jira project key to use for this External Ticket
   *
   * @example ABC
   */
  projectKey?: string
  /*
   * The title for this External Ticket
   *
   * @example A new ticket
   */
  title?: string
}

/**
 * @example {"id":"abcdef1234567890ghijkl"}
 */
export type IDResult = {
  /*
   * Resource identifier
   *
   * @example abcdef1234567890ghijkl
   * @pattern ^[a-zA-Z0-9_-]{22}$
   */
  id: string
}

/**
 * @example {"additional":"{\"name\": \"value\"}","connectorId":"my_jira_connector","module":"sto","service":"Jira"}
 */
export type SaveSettingRequestBody = {
  /*
   * Additional settings
   *
   * @example {"name": "value"}
   */
  additional?: string
  /*
   * The Harness connector ID to use for communication with the ticket provider
   *
   * @example my_jira_connector
   */
  connectorId: string
  /*
   * The Harness module for which these settings should apply
   *
   * @example sto
   */
  module?: string
  /*
   * The ticket provider to use
   *
   * @example Jira
   */
  service: 'Jira'
}

/**
 * @example {"commit":"96381692bf3a2bd7904769c6886e832435768b57","version":"v0.123.0"}
 */
export type ServiceVersion = {
  /*
   * Build identifier
   *
   * @example 96381692bf3a2bd7904769c6886e832435768b57
   */
  commit: string
  /*
   * Version number
   *
   * @example v0.123.0
   */
  version: string
}

export type TicketsCreateTicketResponseBody = IDResult
