/*
 * Copyright 2023 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Shield 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.
 */

/**
 * Generated by @openapi-codegen
 *
 * @version 0.1.0-beta
 */
/**
 * @example {"message":"Bad Request: accountId parameter is required","status":400}
 */
export type BadRequest = {
  /*
   * @example Bad Request: accountId parameter is required
   */
  message: string
  /*
   * @default 400
   * @example 400
   * @format int64
   */
  status?: number
}

/**
 * @example {"description":"This is the very long ticket description...","exists":false,"externalId":"ABC-1234","identifiers":{"idName":["value1","value2","value3"]},"issueType":"Bug","module":"sto","priority":"High","projectKey":"ABC","title":"A new ticket"}
 */
export type CreateTicketRequestBody = {
  /*
   * The description for this External Ticket
   *
   * @example This is the very long ticket description...
   */
  description?: string
  /*
   * Indicates the ticket already exists on the ticket provider
   *
   * @example false
   */
  exists?: boolean
  /*
   * The ID used to identify this External Ticket in the ticket provider. Only used if the "exists" field is true.
   *
   * @example ABC-1234
   */
  externalId?: string
  /*
   * Identifier(s) to associate with this ticket, in "key":"value" and/or "key":ArrayOf("values"...) form
   *
   * @example {"idName":["value1","value2","value3"]}
   */
  identifiers: {
    [key: string]: any
  }
  /*
   * The Jira issue type to use for this External Ticket
   *
   * @example Bug
   */
  issueType?: string
  /*
   * The Harness module responsible for this ticket
   *
   * @example sto
   */
  module: string
  /*
   * The priority to use for this External Ticket
   *
   * @example High
   */
  priority?: string
  /*
   * The Jira project key to use for this External Ticket
   *
   * @example ABC
   */
  projectKey?: string
  /*
   * The title for this External Ticket
   *
   * @example A new ticket
   */
  title?: string
}

/**
 * @example {"id":"abcdef1234567890ghijkl"}
 */
export type IDResult = {
  /*
   * Resource identifier
   *
   * @example abcdef1234567890ghijkl
   * @pattern ^[a-zA-Z0-9_-]{22}$
   */
  id: string
}

/**
 * @example {"link":"","page":4,"pageSize":20,"totalItems":230,"totalPages":12}
 */
export type Pagination = {
  /*
   * Link-based paging
   *
   * @example
   */
  link?: string
  /*
   * Page number (starting from 0)
   *
   * @example 4
   * @format int64
   */
  page: number
  /*
   * Requested page size
   *
   * @example 20
   * @format int64
   */
  pageSize: number
  /*
   * Total results available
   *
   * @example 230
   * @format int64
   */
  totalItems: number
  /*
   * Total pages available
   *
   * @example 12
   * @format int64
   */
  totalPages: number
}

/**
 * @example {"additional":{"name":"value"},"connectorId":"my_jira_connector","module":"sto","service":"Jira"}
 */
export type SaveSettingRequestBody = {
  /*
   * Additional settings
   *
   * @example {"name":"value"}
   */
  additional?: {
    [key: string]: string
  }
  /*
   * The Harness connector ID to use for communication with the ticket provider
   *
   * @example my_jira_connector
   */
  connectorId: string
  /*
   * The Harness module for which these settings should apply
   *
   * @example sto
   */
  module?: string
  /*
   * The ticket provider to use
   *
   * @example Jira
   */
  service: 'Jira'
}

/**
 * @example {"commit":"96381692bf3a2bd7904769c6886e832435768b57","version":"v0.123.0"}
 */
export type ServiceVersion = {
  /*
   * Build identifier
   *
   * @example 96381692bf3a2bd7904769c6886e832435768b57
   */
  commit: string
  /*
   * Version number
   *
   * @example v0.123.0
   */
  version: string
}

/**
 * @example {"additional":{"name":"value"},"connectorId":"my_jira_connector","created":1651578240,"lastModified":1651578240,"module":"sto","service":"Jira"}
 */
export type Setting = {
  /*
   * Additional settings
   *
   * @example {"name":"value"}
   */
  additional?: {
    [key: string]: string
  }
  /*
   * The Harness connector ID to use for communication with the ticket provider
   *
   * @example my_jira_connector
   */
  connectorId: string
  /*
   * Unix timestamp at which the resource was created
   *
   * @example 1651578240
   * @format int64
   */
  created?: number
  /*
   * Unix timestamp at which the resource was most recently modified
   *
   * @example 1651578240
   * @format int64
   */
  lastModified?: number
  /*
   * The Harness module for which these settings should apply
   *
   * @example sto
   */
  module?: string
  /*
   * The ticket provider to use
   *
   * @example Jira
   */
  service: 'Jira'
}

/**
 * Information about an External Ticket
 *
 * @example {"created":1651578240,"description":"This is the very long ticket description...","exists":false,"externalId":"ABC-1234","id":"abcdef1234567890ghijkl","identifiers":{"idName":["value1","value2","value3"]},"issueType":"Bug","lastModified":1651578240,"module":"sto","orgId":"example_org","priority":"High","projectId":"example_project","projectKey":"ABC","title":"A new ticket"}
 */
export type Ticket = {
  /*
   * Unix timestamp at which the resource was created
   *
   * @example 1651578240
   * @format int64
   */
  created?: number
  /*
   * The description for this External Ticket
   *
   * @example This is the very long ticket description...
   */
  description?: string
  /*
   * Indicates the ticket already exists on the ticket provider
   *
   * @example false
   */
  exists?: boolean
  /*
   * The ID used to identify this External Ticket in the ticket provider. Only used if the "exists" field is true.
   *
   * @example ABC-1234
   */
  externalId?: string
  /*
   * Resource identifier
   *
   * @example abcdef1234567890ghijkl
   * @pattern ^[a-zA-Z0-9_-]{22}$
   */
  id?: string
  /*
   * Identifier(s) to associate with this ticket, in "key":"value" and/or "key":ArrayOf("values"...) form
   *
   * @example {"idName":["value1","value2","value3"]}
   */
  identifiers: {
    [key: string]: any
  }
  /*
   * The Jira issue type to use for this External Ticket
   *
   * @example Bug
   */
  issueType?: string
  /*
   * Unix timestamp at which the resource was most recently modified
   *
   * @example 1651578240
   * @format int64
   */
  lastModified?: number
  /*
   * The Harness module responsible for this ticket
   *
   * @example sto
   */
  module: string
  /*
   * Harness Organization ID
   *
   * @example example_org
   * @pattern ^[A-Za-z_][A-Za-z0-9_]*$
   * @maxLength 128
   */
  orgId?: string
  /*
   * The priority to use for this External Ticket
   *
   * @example High
   */
  priority?: string
  /*
   * Harness Project ID
   *
   * @example example_project
   * @pattern ^[A-Za-z_][A-Za-z0-9_]*$
   * @maxLength 128
   */
  projectId?: string
  /*
   * The Jira project key to use for this External Ticket
   *
   * @example ABC
   */
  projectKey?: string
  /*
   * The title for this External Ticket
   *
   * @example A new ticket
   */
  title?: string
}

export type TicketsCreateTicketResponseBody = IDResult

/**
 * @example {"pagination":{"link":"","page":4,"pageSize":20,"totalItems":230,"totalPages":12},"results":[{"created":1651578240,"description":"This is the very long ticket description...","exists":false,"externalId":"ABC-1234","id":"abcdef1234567890ghijkl","identifiers":{"idName":["value1","value2","value3"]},"issueType":"Bug","lastModified":1651578240,"module":"sto","orgId":"example_org","priority":"High","projectId":"example_project","projectKey":"ABC","title":"A new ticket"},{"created":1651578240,"description":"This is the very long ticket description...","exists":false,"externalId":"ABC-1234","id":"abcdef1234567890ghijkl","identifiers":{"idName":["value1","value2","value3"]},"issueType":"Bug","lastModified":1651578240,"module":"sto","orgId":"example_org","priority":"High","projectId":"example_project","projectKey":"ABC","title":"A new ticket"}]}
 */
export type TicketsListTicketsResponseBody = {
  pagination: Pagination
  /*
   * @example {"created":1651578240,"description":"This is the very long ticket description...","exists":false,"externalId":"ABC-1234","id":"abcdef1234567890ghijkl","identifiers":{"idName":["value1","value2","value3"]},"issueType":"Bug","lastModified":1651578240,"module":"sto","orgId":"example_org","priority":"High","projectId":"example_project","projectKey":"ABC","title":"A new ticket"}
   * @example {"created":1651578240,"description":"This is the very long ticket description...","exists":false,"externalId":"ABC-1234","id":"abcdef1234567890ghijkl","identifiers":{"idName":["value1","value2","value3"]},"issueType":"Bug","lastModified":1651578240,"module":"sto","orgId":"example_org","priority":"High","projectId":"example_project","projectKey":"ABC","title":"A new ticket"}
   * @example {"created":1651578240,"description":"This is the very long ticket description...","exists":false,"externalId":"ABC-1234","id":"abcdef1234567890ghijkl","identifiers":{"idName":["value1","value2","value3"]},"issueType":"Bug","lastModified":1651578240,"module":"sto","orgId":"example_org","priority":"High","projectId":"example_project","projectKey":"ABC","title":"A new ticket"}
   * @example {"created":1651578240,"description":"This is the very long ticket description...","exists":false,"externalId":"ABC-1234","id":"abcdef1234567890ghijkl","identifiers":{"idName":["value1","value2","value3"]},"issueType":"Bug","lastModified":1651578240,"module":"sto","orgId":"example_org","priority":"High","projectId":"example_project","projectKey":"ABC","title":"A new ticket"}
   */
  results: Ticket[]
}
