/*
 * Copyright 2022 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Shield 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.
 */
/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { ServicesV2YamlMetadataDto } from '../schemas/ServicesV2YamlMetadataDto'

export interface ResponseServicesV2YamlMetadataDto {
  correlationId?: string
  data?: ServicesV2YamlMetadataDto
  metaData?: { [key: string]: any }
  status?: 'ERROR' | 'FAILURE' | 'SUCCESS'
}
