/*
 * Copyright 2023 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Shield 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt.
 */
/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { CacheResponseMetadata } from '../schemas/CacheResponseMetadata'
import type { EntityGitDetails } from '../schemas/EntityGitDetails'

export interface ServiceResponseDto {
  accountId?: string
  cacheResponseMetadataDTO?: CacheResponseMetadata
  connectorRef?: string
  deleted?: boolean
  description?: string
  entityGitDetails?: EntityGitDetails
  fallbackBranch?: string
  identifier?: string
  name?: string
  orgIdentifier?: string
  projectIdentifier?: string
  storeType?: 'INLINE' | 'REMOTE'
  tags?: { [key: string]: string }
  v2Service?: boolean
  yaml?: string
}
