export enum PLG_EXPERIMENTS {
  NO_INTENT_TEST = 'NO_INTENT_TEST',
  PLG_SERVICE_DELEGATE_TEST = 'PLG_SERVICE_DELEGATE_TEST',
  CD_GET_STARTED = 'CD_GET_STARTED'
}

export const EXPOSURE_EVENT = '$exposure'
